# This is a workflow to run our linting and unit tests for windows, mac, and linux

name: Linting and Unit Tests

# Triggers
on:
  # Trigger on commits to develop and releases
  push:
    branches: 
      - 'develop' 
      - '*.latest' 
      - 'releases/*'
  pull_request_target: # Trigger for all PRs
  workflow_dispatch: # Allow manual triggers

jobs:
  Linting:
    runs-on: ubuntu-latest #no need to run on every OS
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: 'Install dependencies'
      run: python -m pip install --upgrade pip && pip install tox
      
    - name: 'Linting'
      run: tox -e mypy,flake8 -- -v
      
  UnitTest:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.6
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Setup Python 3.7
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Setup Python 3.8
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: 'Install dependencies'
      run: python -m pip install --upgrade pip && pip install tox

    - name: 'Run unit tests'
      run: tox -p -e py36,py37,py38
