# This is a workflow to run our unit and integration tests for windows and mac

name: dbt Tests

# Triggers
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: 
      - 'develop' 
      - '*.latest' 
      - 'pr/*'
      - 'releases/*'
  pull_request_target:  
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
      
  PostgresIntegrationTest:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    environment: 'Postgres'
    steps:
    - name: 'Install postgresql and set up database'
      run: |
          brew services start postgresql
          psql
      

