# This is a workflow to run our unit and integration tests for windows and mac

name: dbt Tests

# Triggers
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: 
      - 'develop' 
      - '*.latest' 
      - 'pr/*'
      - 'releases/*'
  pull_request_target:  
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  UnitTest:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.6', '3.7', '3.8']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: 'Install dependencies'
      run: python -m pip install --upgrade pip && pip install tox

    - name: 'Run unit tests'
      run: python -m tox -e py -- -v
